const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800" },
    price: 1500, location: "Malibu", country: "United States", category: "beach",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800" },
    price: 1200, location: "New York City", country: "United States", category: "iconic cities",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800" },
    price: 1000, location: "Aspen", country: "United States", category: "mountains",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800" },
    price: 2500, location: "Florence", country: "Italy", category: "rooms",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800" },
    price: 800, location: "Portland", country: "United States", category: "camping",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800" },
    price: 2000, location: "Cancun", country: "Mexico", category: "beach",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800" },
    price: 900, location: "Lake Tahoe", country: "United States", category: "rooms",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?w=800" },
    price: 3500, location: "Los Angeles", country: "United States", category: "iconic cities",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?w=800" },
    price: 3000, location: "Verbier", country: "Switzerland", category: "mountains",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800" },
    price: 4000, location: "Serengeti National Park", country: "Tanzania", category: "trending",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800" },
    price: 1800, location: "Amsterdam", country: "Netherlands", category: "iconic cities",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive vacation experience.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?w=800" },
    price: 10000, location: "Fiji", country: "Fiji", category: "trending",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint cottage with a thatched roof.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800" },
    price: 1200, location: "Cotswolds", country: "United Kingdom", category: "rooms",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800" },
    price: 5000, location: "Dubai", country: "United Arab Emirates", category: "trending",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali with a private pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?w=800" },
    price: 1800, location: "Bali", country: "Indonesia", category: "beach",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?w=800" },
    price: 1500, location: "Banff", country: "Canada", category: "mountains",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise with a private infinity pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?w=800" },
    price: 3000, location: "Phuket", country: "Thailand", category: "amazing pools",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?w=800" },
    price: 4000, location: "Scottish Highlands", country: "United Kingdom", category: "castles",
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in this overwater villa with stunning views of the Indian Ocean.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800" },
    price: 6000, location: "Maldives", country: "Maldives", category: "amazing pools",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest of Costa Rica.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?w=800" },
    price: 750, location: "Costa Rica", country: "Costa Rica", category: "camping",
  },
  {
    title: "Glass Dome in Norway",
    description: "Sleep under the northern lights in a stunning heated glass dome.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800" },
    price: 5000, location: "Tromsø", country: "Norway", category: "domes",
  },
  {
    title: "Houseboat in Kerala",
    description: "Drift through the serene backwaters of Kerala on a traditional houseboat.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800" },
    price: 3200, location: "Alleppey", country: "India", category: "boats",
  },
  {
    title: "Arctic Cabin in Finland",
    description: "A snug log cabin on the edge of a frozen lake in Finnish Lapland.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800" },
    price: 4200, location: "Lapland", country: "Finland", category: "arctic",
  },
  {
    title: "Organic Farm Stay in Coorg",
    description: "Wake up to birdsong on a working coffee and spice farm in the hills of Coorg.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800" },
    price: 900, location: "Coorg", country: "India", category: "farms",
  },
];

module.exports = { data: sampleListings };